version: '3.8'
services:
  devcontainer:
    container_name: info-5940-devcontainertest
    build:
      dockerfile: Dockerfile
      target: devcontainer
    environment:
      AWS_PROFILE: aaii
      AZURE_OPENAI_API_KEY: 9797c6d4450640dca4528968e7e5ab3c
      AZURE_OPENAI_ENDPOINT: https://ai-info5940892642799052.openai.azure.com/
      AZURE_OPENAI_MODEL_DEPLOYMENT: gpt-4o
      OPENAI_API_KEY: 9797c6d4450640dca4528968e7e5ab3c
    volumes:
      - '$HOME/.aws:/root/.aws'
      - '.:/workspace'
